@baseAddress = http://localhost:5192

###
GET {{baseAddress}}/api/categories
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "Name": "Category1"
}
###